name: Trigger auto deployment for sampleapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/sampleapp-AutoDeployTrigger-57590bab-e9fb-4ca8-8cf4-39b18ed9413e.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SAMPLEAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.SAMPLEAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SAMPLEAPP_REGISTRY_PASSWORD }}
          containerAppName: sampleapp
          resourceGroup: ContainerAppGroup
          imageToBuild: sonusathyadas/demo-sample-app:${{ github.sha }}
          
            

     

